table 'Member Names'
	lineageTag: 5dfb4907-c410-45f6-a686-28fb70f4e341

	column Member_Claim_Id
		dataType: int64
		formatString: 0
		lineageTag: 61c616ad-f9a7-447a-9003-c5dfc66394b1
		summarizeBy: none
		sourceColumn: Member_Claim_Id

		annotation SummarizationSetBy = Automatic

	column Member_Name
		dataType: string
		lineageTag: 7c2c49ba-1850-48f1-8bbc-a38e374fea40
		summarizeBy: none
		sourceColumn: Member_Name

		annotation SummarizationSetBy = Automatic

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\uvishnu\OneDrive - ZeOmega\Desktop\Members.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Member_Claim_Id", Int64.Type}, {"Member_Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

