{
  "compatibilityLevel": 1570,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "FactObservation",
        "columns": [
          {
            "name": "observation_key",
            "dataType": "string",
            "sourceColumn": "observation_key"
          },
          {
            "name": "patient_key",
            "dataType": "string",
            "sourceColumn": "patient_key"
          },
          {
            "name": "provider_key",
            "dataType": "string",
            "sourceColumn": "provider_key"
          },
          {
            "name": "organization_key",
            "dataType": "string",
            "sourceColumn": "organization_key"
          },
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key"
          },
          {
            "name": "observation_identifier",
            "dataType": "string",
            "sourceColumn": "observation_identifier"
          },
          {
            "name": "observation_code",
            "dataType": "string",
            "sourceColumn": "observation_code"
          },
          {
            "name": "observation_status",
            "dataType": "string",
            "sourceColumn": "observation_status"
          },
          {
            "name": "value_codeable_concept",
            "dataType": "string",
            "sourceColumn": "value_codeable_concept"
          },
          {
            "name": "value_boolean",
            "dataType": "boolean",
            "sourceColumn": "value_boolean"
          },
          {
            "name": "value_quantity",
            "dataType": "double",
            "sourceColumn": "value_quantity"
          },
          {
            "name": "decision_rationale",
            "dataType": "string",
            "sourceColumn": "decision_rationale"
          },
          {
            "name": "dismissal_rationale",
            "dataType": "string",
            "sourceColumn": "dismissal_rationale"
          },
          {
            "name": "processing_priority",
            "dataType": "string",
            "sourceColumn": "processing_priority"
          }
        ],
        "measures": [],
        "partitions": [
          {
            "name": "FactObservation-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRecords({\n        [observation_key = 1, patient_key = 1, provider_key = 1, organization_key = 1, date_key = 20260115, observation_identifier = \"Mock observation_identifier 1\", observation_code = \"Mock observation_code 1\", observation_status = \"Mock observation_status 1\", value_codeable_concept = \"Mock value_codeable_concept 1\", value_boolean = true, value_quantity = 1.5, decision_rationale = \"Mock decision_rationale 1\", dismissal_rationale = \"Mock dismissal_rationale 1\", processing_priority = \"Mock processing_priority 1\"],\n        [observation_key = 2, patient_key = 2, provider_key = 2, organization_key = 2, date_key = 20260220, observation_identifier = \"Mock observation_identifier 2\", observation_code = \"Mock observation_code 2\", observation_status = \"Mock observation_status 2\", value_codeable_concept = \"Mock value_codeable_concept 2\", value_boolean = false, value_quantity = 3.0, decision_rationale = \"Mock decision_rationale 2\", dismissal_rationale = \"Mock dismissal_rationale 2\", processing_priority = \"Mock processing_priority 2\"],\n        [observation_key = 3, patient_key = 3, provider_key = 3, organization_key = 3, date_key = 20260310, observation_identifier = \"Mock observation_identifier 3\", observation_code = \"Mock observation_code 3\", observation_status = \"Mock observation_status 3\", value_codeable_concept = \"Mock value_codeable_concept 3\", value_boolean = true, value_quantity = 4.5, decision_rationale = \"Mock decision_rationale 3\", dismissal_rationale = \"Mock dismissal_rationale 3\", processing_priority = \"Mock processing_priority 3\"],\n        [observation_key = 4, patient_key = 4, provider_key = 4, organization_key = 4, date_key = 20260425, observation_identifier = \"Mock observation_identifier 4\", observation_code = \"Mock observation_code 4\", observation_status = \"Mock observation_status 4\", value_codeable_concept = \"Mock value_codeable_concept 4\", value_boolean = false, value_quantity = 6.0, decision_rationale = \"Mock decision_rationale 4\", dismissal_rationale = \"Mock dismissal_rationale 4\", processing_priority = \"Mock processing_priority 4\"],\n        [observation_key = 5, patient_key = 5, provider_key = 5, organization_key = 5, date_key = 20260515, observation_identifier = \"Mock observation_identifier 5\", observation_code = \"Mock observation_code 5\", observation_status = \"Mock observation_status 5\", value_codeable_concept = \"Mock value_codeable_concept 5\", value_boolean = true, value_quantity = 7.5, decision_rationale = \"Mock decision_rationale 5\", dismissal_rationale = \"Mock dismissal_rationale 5\", processing_priority = \"Mock processing_priority 5\"]\n    }),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source, {\n        {\"observation_key\", type text},\n        {\"patient_key\", type text},\n        {\"provider_key\", type text},\n        {\"organization_key\", type text},\n        {\"date_key\", type text},\n        {\"observation_identifier\", type text},\n        {\"observation_code\", type text},\n        {\"observation_status\", type text},\n        {\"value_codeable_concept\", type text},\n        {\"value_boolean\", type logical},\n        {\"value_quantity\", type number},\n        {\"decision_rationale\", type text},\n        {\"dismissal_rationale\", type text},\n        {\"processing_priority\", type text}\n    })\nin\n    #\"Changed Type\""
            }
          }
        ],
        "description": "Captures operational quality events, grievances, organization determinations, reconsiderations, health risk assessments (HRAs), and provider payments. Strictly isolated from prior authorization metrics and service level data collection reports per organizational decision c19cd11c."
      },
      {
        "name": "FactEncounter",
        "columns": [
          {
            "name": "encounter_key",
            "dataType": "string",
            "sourceColumn": "encounter_key"
          },
          {
            "name": "patient_key",
            "dataType": "string",
            "sourceColumn": "patient_key"
          },
          {
            "name": "provider_key",
            "dataType": "string",
            "sourceColumn": "provider_key"
          },
          {
            "name": "organization_key",
            "dataType": "string",
            "sourceColumn": "organization_key"
          },
          {
            "name": "admission_date_key",
            "dataType": "string",
            "sourceColumn": "admission_date_key"
          },
          {
            "name": "discharge_date_key",
            "dataType": "string",
            "sourceColumn": "discharge_date_key"
          },
          {
            "name": "encounter_class",
            "dataType": "string",
            "sourceColumn": "encounter_class"
          },
          {
            "name": "discharge_disposition",
            "dataType": "string",
            "sourceColumn": "discharge_disposition"
          }
        ],
        "measures": [],
        "partitions": [
          {
            "name": "FactEncounter-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRecords({\n        [encounter_key = 1, patient_key = 1, provider_key = 1, organization_key = 1, admission_date_key = 1, discharge_date_key = 1, encounter_class = \"AMB\", discharge_disposition = \"Mock discharge_disposition 1\"],\n        [encounter_key = 2, patient_key = 2, provider_key = 2, organization_key = 2, admission_date_key = 2, discharge_date_key = 2, encounter_class = \"IMP\", discharge_disposition = \"Mock discharge_disposition 2\"],\n        [encounter_key = 3, patient_key = 3, provider_key = 3, organization_key = 3, admission_date_key = 3, discharge_date_key = 3, encounter_class = \"AMB\", discharge_disposition = \"Mock discharge_disposition 3\"],\n        [encounter_key = 4, patient_key = 4, provider_key = 4, organization_key = 4, admission_date_key = 4, discharge_date_key = 4, encounter_class = \"EMER\", discharge_disposition = \"Mock discharge_disposition 4\"],\n        [encounter_key = 5, patient_key = 5, provider_key = 5, organization_key = 5, admission_date_key = 5, discharge_date_key = 5, encounter_class = \"AMB\", discharge_disposition = \"Mock discharge_disposition 5\"]\n    }),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source, {\n        {\"encounter_key\", type text},\n        {\"patient_key\", type text},\n        {\"provider_key\", type text},\n        {\"organization_key\", type text},\n        {\"admission_date_key\", type text},\n        {\"discharge_date_key\", type text},\n        {\"encounter_class\", type text},\n        {\"discharge_disposition\", type text}\n    })\nin\n    #\"Changed Type\""
            }
          }
        ],
        "description": "Captures inpatient interactions, hospital admissions, and Skilled Nursing Facility (SNF) stays for D-SNP and general enrollees."
      },
      {
        "name": "FactProcedure",
        "columns": [
          {
            "name": "procedure_key",
            "dataType": "string",
            "sourceColumn": "procedure_key"
          },
          {
            "name": "patient_key",
            "dataType": "string",
            "sourceColumn": "patient_key"
          },
          {
            "name": "provider_key",
            "dataType": "string",
            "sourceColumn": "provider_key"
          },
          {
            "name": "organization_key",
            "dataType": "string",
            "sourceColumn": "organization_key"
          },
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key"
          },
          {
            "name": "procedure_code",
            "dataType": "string",
            "sourceColumn": "procedure_code"
          },
          {
            "name": "procedure_description",
            "dataType": "string",
            "sourceColumn": "procedure_description"
          }
        ],
        "measures": [],
        "partitions": [
          {
            "name": "FactProcedure-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRecords({\n        [procedure_key = 1, patient_key = 1, provider_key = 1, organization_key = 1, date_key = 20260115, procedure_code = \"99213\", procedure_description = \"Office Visit\"],\n        [procedure_key = 2, patient_key = 2, provider_key = 2, organization_key = 2, date_key = 20260220, procedure_code = \"85025\", procedure_description = \"CBC Test\"],\n        [procedure_key = 3, patient_key = 3, provider_key = 3, organization_key = 3, date_key = 20260310, procedure_code = \"CT001\", procedure_description = \"CT Scan\"],\n        [procedure_key = 4, patient_key = 4, provider_key = 4, organization_key = 4, date_key = 20260425, procedure_code = \"RX002\", procedure_description = \"Medication Request\"],\n        [procedure_key = 5, patient_key = 5, provider_key = 5, organization_key = 5, date_key = 20260515, procedure_code = \"99214\", procedure_description = \"Office Visit High\"]\n    }),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source, {\n        {\"procedure_key\", type text},\n        {\"patient_key\", type text},\n        {\"provider_key\", type text},\n        {\"organization_key\", type text},\n        {\"date_key\", type text},\n        {\"procedure_code\", type text},\n        {\"procedure_description\", type text}\n    })\nin\n    #\"Changed Type\""
            }
          }
        ],
        "description": "Captures medical items, services, and supplemental benefits approved and furnished to enrollees."
      },
      {
        "name": "FactMedication",
        "columns": [
          {
            "name": "medication_key",
            "dataType": "string",
            "sourceColumn": "medication_key"
          },
          {
            "name": "patient_key",
            "dataType": "string",
            "sourceColumn": "patient_key"
          },
          {
            "name": "provider_key",
            "dataType": "string",
            "sourceColumn": "provider_key"
          },
          {
            "name": "organization_key",
            "dataType": "string",
            "sourceColumn": "organization_key"
          },
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key"
          },
          {
            "name": "medication_code",
            "dataType": "string",
            "sourceColumn": "medication_code"
          },
          {
            "name": "medication_description",
            "dataType": "string",
            "sourceColumn": "medication_description"
          }
        ],
        "measures": [],
        "partitions": [
          {
            "name": "FactMedication-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRecords({\n        [medication_key = 1, patient_key = 1, provider_key = 1, organization_key = 1, date_key = 20260115, medication_code = \"0001\", medication_description = \"Mock medication_description 1\"],\n        [medication_key = 2, patient_key = 2, provider_key = 2, organization_key = 2, date_key = 20260220, medication_code = \"0002\", medication_description = \"Mock medication_description 2\"],\n        [medication_key = 3, patient_key = 3, provider_key = 3, organization_key = 3, date_key = 20260310, medication_code = \"0003\", medication_description = \"Mock medication_description 3\"],\n        [medication_key = 4, patient_key = 4, provider_key = 4, organization_key = 4, date_key = 20260425, medication_code = \"0004\", medication_description = \"Mock medication_description 4\"],\n        [medication_key = 5, patient_key = 5, provider_key = 5, organization_key = 5, date_key = 20260515, medication_code = \"0005\", medication_description = \"Mock medication_description 5\"]\n    }),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source, {\n        {\"medication_key\", type text},\n        {\"patient_key\", type text},\n        {\"provider_key\", type text},\n        {\"organization_key\", type text},\n        {\"date_key\", type text},\n        {\"medication_code\", type text},\n        {\"medication_description\", type text}\n    })\nin\n    #\"Changed Type\""
            }
          }
        ],
        "description": "Captures Part B drug requests and approvals."
      },
      {
        "name": "DimPatient",
        "columns": [
          {
            "name": "patient_key",
            "dataType": "string",
            "sourceColumn": "patient_key"
          },
          {
            "name": "mbi",
            "dataType": "string",
            "sourceColumn": "mbi"
          },
          {
            "name": "state",
            "dataType": "string",
            "sourceColumn": "state"
          },
          {
            "name": "is_active",
            "dataType": "boolean",
            "sourceColumn": "is_active"
          },
          {
            "name": "deceased_date",
            "dataType": "dateTime",
            "sourceColumn": "deceased_date"
          }
        ],
        "measures": [],
        "partitions": [
          {
            "name": "DimPatient-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRecords({\n        [patient_key = 1, mbi = \"1EG4-TE5-MK2\", state = \"Mock state 1\", is_active = true, deceased_date = #date(2026, 1, 15)],\n        [patient_key = 2, mbi = \"2FH5-UG6-NL3\", state = \"Mock state 2\", is_active = false, deceased_date = #date(2026, 2, 20)],\n        [patient_key = 3, mbi = \"3GJ6-VH7-OM4\", state = \"Mock state 3\", is_active = true, deceased_date = #date(2026, 3, 10)],\n        [patient_key = 4, mbi = \"4HK7-WI8-PN5\", state = \"Mock state 4\", is_active = false, deceased_date = #date(2026, 4, 25)],\n        [patient_key = 5, mbi = \"5JL8-XJ9-QO6\", state = \"Mock state 5\", is_active = true, deceased_date = #date(2026, 5, 15)]\n    }),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source, {\n        {\"patient_key\", type text},\n        {\"mbi\", type text},\n        {\"state\", type text},\n        {\"is_active\", type logical},\n        {\"deceased_date\", type date}\n    })\nin\n    #\"Changed Type\""
            }
          }
        ],
        "description": "Demographic and enrollment status details of the Medicare Advantage enrollees."
      },
      {
        "name": "DimProvider",
        "columns": [
          {
            "name": "provider_key",
            "dataType": "string",
            "sourceColumn": "provider_key"
          },
          {
            "name": "npi",
            "dataType": "string",
            "sourceColumn": "npi"
          },
          {
            "name": "qualification",
            "dataType": "string",
            "sourceColumn": "qualification"
          }
        ],
        "measures": [],
        "partitions": [
          {
            "name": "DimProvider-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRecords({\n        [provider_key = 1, npi = \"NPI11111\", qualification = \"Physician\"],\n        [provider_key = 2, npi = \"NPI22222\", qualification = \"Specialist\"],\n        [provider_key = 3, npi = \"NPI33333\", qualification = \"Physician\"],\n        [provider_key = 4, npi = \"NPI44444\", qualification = \"Specialist\"],\n        [provider_key = 5, npi = \"NPI55555\", qualification = \"Physician\"]\n    }),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source, {\n        {\"provider_key\", type text},\n        {\"npi\", type text},\n        {\"qualification\", type text}\n    })\nin\n    #\"Changed Type\""
            }
          }
        ],
        "description": "Details of healthcare practitioners and providers."
      },
      {
        "name": "DimOrganization",
        "columns": [
          {
            "name": "organization_key",
            "dataType": "string",
            "sourceColumn": "organization_key"
          },
          {
            "name": "contract_number",
            "dataType": "string",
            "sourceColumn": "contract_number"
          },
          {
            "name": "pbp_code",
            "dataType": "string",
            "sourceColumn": "pbp_code"
          },
          {
            "name": "organization_type",
            "dataType": "string",
            "sourceColumn": "organization_type"
          },
          {
            "name": "line_of_business",
            "dataType": "string",
            "sourceColumn": "line_of_business"
          }
        ],
        "measures": [],
        "partitions": [
          {
            "name": "DimOrganization-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRecords({\n        [organization_key = 1, contract_number = \"H1001\", pbp_code = \"Mock pbp_code 1\", organization_type = \"MAO\", line_of_business = \"Mock line_of_business 1\"],\n        [organization_key = 2, contract_number = \"H2002\", pbp_code = \"Mock pbp_code 2\", organization_type = \"MAO\", line_of_business = \"Mock line_of_business 2\"],\n        [organization_key = 3, contract_number = \"H3003\", pbp_code = \"Mock pbp_code 3\", organization_type = \"1876 Cost Plan\", line_of_business = \"Mock line_of_business 3\"],\n        [organization_key = 4, contract_number = \"H4004\", pbp_code = \"Mock pbp_code 4\", organization_type = \"IRE\", line_of_business = \"Mock line_of_business 4\"],\n        [organization_key = 5, contract_number = \"H5005\", pbp_code = \"Mock pbp_code 5\", organization_type = \"Appeals Council\", line_of_business = \"Mock line_of_business 5\"]\n    }),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source, {\n        {\"organization_key\", type text},\n        {\"contract_number\", type text},\n        {\"pbp_code\", type text},\n        {\"organization_type\", type text},\n        {\"line_of_business\", type text}\n    })\nin\n    #\"Changed Type\""
            }
          }
        ],
        "description": "Details of Medicare Advantage Organizations, Plan Sponsors, D-SNPs, and Employer Groups."
      },
      {
        "name": "DimCondition",
        "columns": [
          {
            "name": "condition_key",
            "dataType": "string",
            "sourceColumn": "condition_key"
          },
          {
            "name": "diagnosis_code",
            "dataType": "string",
            "sourceColumn": "diagnosis_code"
          }
        ],
        "measures": [],
        "partitions": [
          {
            "name": "DimCondition-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRecords({\n        [condition_key = 1, diagnosis_code = \"Mock diagnosis_code 1\"],\n        [condition_key = 2, diagnosis_code = \"Mock diagnosis_code 2\"],\n        [condition_key = 3, diagnosis_code = \"Mock diagnosis_code 3\"],\n        [condition_key = 4, diagnosis_code = \"Mock diagnosis_code 4\"],\n        [condition_key = 5, diagnosis_code = \"Mock diagnosis_code 5\"]\n    }),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source, {\n        {\"condition_key\", type text},\n        {\"diagnosis_code\", type text}\n    })\nin\n    #\"Changed Type\""
            }
          }
        ],
        "description": "Diagnosis codes associated with enrollees and determinations."
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "date_key",
            "dataType": "string",
            "sourceColumn": "date_key"
          },
          {
            "name": "date",
            "dataType": "dateTime",
            "sourceColumn": "date"
          },
          {
            "name": "year",
            "dataType": "int64",
            "sourceColumn": "year"
          },
          {
            "name": "quarter",
            "dataType": "string",
            "sourceColumn": "quarter"
          },
          {
            "name": "month",
            "dataType": "string",
            "sourceColumn": "month"
          },
          {
            "name": "day",
            "dataType": "int64",
            "sourceColumn": "day"
          }
        ],
        "measures": [],
        "partitions": [
          {
            "name": "DimDate-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRecords({\n        [date_key = 20260115, date = #date(2026, 1, 15), year = 2026, quarter = 1, month = 1, day = 15],\n        [date_key = 20260220, date = #date(2026, 2, 20), year = 2026, quarter = 1, month = 2, day = 20],\n        [date_key = 20260310, date = #date(2026, 3, 10), year = 2026, quarter = 1, month = 3, day = 10],\n        [date_key = 20260425, date = #date(2026, 4, 25), year = 2026, quarter = 2, month = 4, day = 25],\n        [date_key = 20260515, date = #date(2026, 5, 15), year = 2026, quarter = 2, month = 5, day = 15]\n    }),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source, {\n        {\"date_key\", type text},\n        {\"date\", type date},\n        {\"year\", Int64.Type},\n        {\"quarter\", type text},\n        {\"month\", type text},\n        {\"day\", Int64.Type}\n    })\nin\n    #\"Changed Type\""
            }
          }
        ],
        "description": "Standard date dimension for time-based analysis and reporting periods."
      },
      {
        "name": "_Measures",
        "columns": [
          {
            "name": "_placeholder",
            "dataType": "string",
            "sourceColumn": "_placeholder",
            "isHidden": true
          }
        ],
        "measures": [
          {
            "name": "Total Org Determinations Override",
            "expression": "COUNTROWS(FactObservation)",
            "description": "Total count of unique Organization Determinations."
          },
          {
            "name": "Adverse Decision Rate",
            "expression": "DIVIDE(CALCULATE(COUNTROWS(FactObservation), FactObservation[disposition] = \"Adverse\"), [Total Org Determinations Override], 0)",
            "description": "Percentage of determinations that resulted in adverse decisions."
          },
          {
            "name": "Average Turnaround Time",
            "expression": "DIVIDE(SUM(FactObservation[determination_key]), 2, 0)",
            "description": "Average turnaround time for organization determinations in days."
          },
          {
            "name": "Clean Claim Rate",
            "expression": "DIVIDE(CALCULATE(COUNTROWS(FactObservation), FactObservation[is_clean_claim] = TRUE), COUNTROWS(FactObservation), 0)",
            "description": "Percentage of clean claims submitted."
          },
          {
            "name": "Missing Data %",
            "expression": "DIVIDE(CALCULATE(COUNTROWS(FactObservation), ISBLANK(FactObservation[od_number])), COUNTROWS(FactObservation), 0)",
            "description": "Percentage of records missing key identifying fields."
          },
          {
            "name": "Validation Errors",
            "expression": "CALCULATE(COUNTROWS(FactObservation), FactObservation[were_internal_plan_criteria_applied] = FALSE)",
            "description": "Total count of validation warnings or errors in data."
          },
          {
            "name": "Data Quality Score",
            "expression": "0.98 - DIVIDE([Validation Errors], COUNTROWS(FactObservation), 0)",
            "description": "Composite score representing data completeness and validation rate."
          },
          {
            "name": "Quality Trend",
            "expression": "[Data Quality Score]",
            "description": "Historical data quality score trend."
          }
        ],
        "partitions": [
          {
            "name": "_Measures-partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRecords({\n        [_placeholder = \"Mock _placeholder 1\"],\n        [_placeholder = \"Mock _placeholder 2\"],\n        [_placeholder = \"Mock _placeholder 3\"],\n        [_placeholder = \"Mock _placeholder 4\"],\n        [_placeholder = \"Mock _placeholder 5\"]\n    }),\n    #\"Changed Type\" = Table.TransformColumnTypes(Source, {\n        {\"_placeholder\", type text}\n    })\nin\n    #\"Changed Type\""
            }
          }
        ],
        "description": "Consolidated business and compliance measures."
      }
    ],
    "relationships": [
      {
        "name": "FactObservation_DimPatient_patient_key",
        "fromTable": "FactObservation",
        "fromColumn": "patient_key",
        "toTable": "DimPatient",
        "toColumn": "patient_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactObservation_DimProvider_provider_key",
        "fromTable": "FactObservation",
        "fromColumn": "provider_key",
        "toTable": "DimProvider",
        "toColumn": "provider_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactObservation_DimOrganization_organization_key",
        "fromTable": "FactObservation",
        "fromColumn": "organization_key",
        "toTable": "DimOrganization",
        "toColumn": "organization_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactObservation_DimDate_date_key",
        "fromTable": "FactObservation",
        "fromColumn": "date_key",
        "toTable": "DimDate",
        "toColumn": "date_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactEncounter_DimPatient_patient_key",
        "fromTable": "FactEncounter",
        "fromColumn": "patient_key",
        "toTable": "DimPatient",
        "toColumn": "patient_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactEncounter_DimProvider_provider_key",
        "fromTable": "FactEncounter",
        "fromColumn": "provider_key",
        "toTable": "DimProvider",
        "toColumn": "provider_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactEncounter_DimOrganization_organization_key",
        "fromTable": "FactEncounter",
        "fromColumn": "organization_key",
        "toTable": "DimOrganization",
        "toColumn": "organization_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactEncounter_DimDate_admission_date_key",
        "fromTable": "FactEncounter",
        "fromColumn": "admission_date_key",
        "toTable": "DimDate",
        "toColumn": "date_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactProcedure_DimPatient_patient_key",
        "fromTable": "FactProcedure",
        "fromColumn": "patient_key",
        "toTable": "DimPatient",
        "toColumn": "patient_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactProcedure_DimProvider_provider_key",
        "fromTable": "FactProcedure",
        "fromColumn": "provider_key",
        "toTable": "DimProvider",
        "toColumn": "provider_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactProcedure_DimOrganization_organization_key",
        "fromTable": "FactProcedure",
        "fromColumn": "organization_key",
        "toTable": "DimOrganization",
        "toColumn": "organization_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactProcedure_DimDate_date_key",
        "fromTable": "FactProcedure",
        "fromColumn": "date_key",
        "toTable": "DimDate",
        "toColumn": "date_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactMedication_DimPatient_patient_key",
        "fromTable": "FactMedication",
        "fromColumn": "patient_key",
        "toTable": "DimPatient",
        "toColumn": "patient_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactMedication_DimProvider_provider_key",
        "fromTable": "FactMedication",
        "fromColumn": "provider_key",
        "toTable": "DimProvider",
        "toColumn": "provider_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactMedication_DimOrganization_organization_key",
        "fromTable": "FactMedication",
        "fromColumn": "organization_key",
        "toTable": "DimOrganization",
        "toColumn": "organization_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      },
      {
        "name": "FactMedication_DimDate_date_key",
        "fromTable": "FactMedication",
        "fromColumn": "date_key",
        "toTable": "DimDate",
        "toColumn": "date_key",
        "crossFilteringBehavior": "oneDirection",
        "isActive": true
      }
    ]
  }
}