model Model
	compatibilityLevel: 1570
	culture: en-US

table FactObservation
	// Description: Captures operational quality events, grievances, organization determinations, reconsiderations, health risk assessments (HRAs), and provider payments. Strictly isolated from prior authorization metrics and service level data collection reports per organizational decision c19cd11c.
	column observation_key
		dataType: string
		sourceColumn: observation_key
	column patient_key
		dataType: string
		sourceColumn: patient_key
	column provider_key
		dataType: string
		sourceColumn: provider_key
	column organization_key
		dataType: string
		sourceColumn: organization_key
	column date_key
		dataType: string
		sourceColumn: date_key
	column observation_identifier
		dataType: string
		sourceColumn: observation_identifier
	column observation_code
		dataType: string
		sourceColumn: observation_code
	column observation_status
		dataType: string
		sourceColumn: observation_status
	column value_codeable_concept
		dataType: string
		sourceColumn: value_codeable_concept
	column value_boolean
		dataType: boolean
		sourceColumn: value_boolean
	column value_quantity
		dataType: double
		sourceColumn: value_quantity
	column decision_rationale
		dataType: string
		sourceColumn: decision_rationale
	column dismissal_rationale
		dataType: string
		sourceColumn: dismissal_rationale
	column processing_priority
		dataType: string
		sourceColumn: processing_priority
	partition FactObservation-partition = m
		mode: import
		source =
			let
			    Source = Table.FromRecords({
			        [observation_key = 1, patient_key = 1, provider_key = 1, organization_key = 1, date_key = 20260115, observation_identifier = "Mock observation_identifier 1", observation_code = "Mock observation_code 1", observation_status = "Mock observation_status 1", value_codeable_concept = "Mock value_codeable_concept 1", value_boolean = true, value_quantity = 1.5, decision_rationale = "Mock decision_rationale 1", dismissal_rationale = "Mock dismissal_rationale 1", processing_priority = "Mock processing_priority 1"],
			        [observation_key = 2, patient_key = 2, provider_key = 2, organization_key = 2, date_key = 20260220, observation_identifier = "Mock observation_identifier 2", observation_code = "Mock observation_code 2", observation_status = "Mock observation_status 2", value_codeable_concept = "Mock value_codeable_concept 2", value_boolean = false, value_quantity = 3.0, decision_rationale = "Mock decision_rationale 2", dismissal_rationale = "Mock dismissal_rationale 2", processing_priority = "Mock processing_priority 2"],
			        [observation_key = 3, patient_key = 3, provider_key = 3, organization_key = 3, date_key = 20260310, observation_identifier = "Mock observation_identifier 3", observation_code = "Mock observation_code 3", observation_status = "Mock observation_status 3", value_codeable_concept = "Mock value_codeable_concept 3", value_boolean = true, value_quantity = 4.5, decision_rationale = "Mock decision_rationale 3", dismissal_rationale = "Mock dismissal_rationale 3", processing_priority = "Mock processing_priority 3"],
			        [observation_key = 4, patient_key = 4, provider_key = 4, organization_key = 4, date_key = 20260425, observation_identifier = "Mock observation_identifier 4", observation_code = "Mock observation_code 4", observation_status = "Mock observation_status 4", value_codeable_concept = "Mock value_codeable_concept 4", value_boolean = false, value_quantity = 6.0, decision_rationale = "Mock decision_rationale 4", dismissal_rationale = "Mock dismissal_rationale 4", processing_priority = "Mock processing_priority 4"],
			        [observation_key = 5, patient_key = 5, provider_key = 5, organization_key = 5, date_key = 20260515, observation_identifier = "Mock observation_identifier 5", observation_code = "Mock observation_code 5", observation_status = "Mock observation_status 5", value_codeable_concept = "Mock value_codeable_concept 5", value_boolean = true, value_quantity = 7.5, decision_rationale = "Mock decision_rationale 5", dismissal_rationale = "Mock dismissal_rationale 5", processing_priority = "Mock processing_priority 5"]
			    }),
			    #"Changed Type" = Table.TransformColumnTypes(Source, {
			        {"observation_key", type text},
			        {"patient_key", type text},
			        {"provider_key", type text},
			        {"organization_key", type text},
			        {"date_key", type text},
			        {"observation_identifier", type text},
			        {"observation_code", type text},
			        {"observation_status", type text},
			        {"value_codeable_concept", type text},
			        {"value_boolean", type logical},
			        {"value_quantity", type number},
			        {"decision_rationale", type text},
			        {"dismissal_rationale", type text},
			        {"processing_priority", type text}
			    })
			in
			    #"Changed Type"

table FactEncounter
	// Description: Captures inpatient interactions, hospital admissions, and Skilled Nursing Facility (SNF) stays for D-SNP and general enrollees.
	column encounter_key
		dataType: string
		sourceColumn: encounter_key
	column patient_key
		dataType: string
		sourceColumn: patient_key
	column provider_key
		dataType: string
		sourceColumn: provider_key
	column organization_key
		dataType: string
		sourceColumn: organization_key
	column admission_date_key
		dataType: string
		sourceColumn: admission_date_key
	column discharge_date_key
		dataType: string
		sourceColumn: discharge_date_key
	column encounter_class
		dataType: string
		sourceColumn: encounter_class
	column discharge_disposition
		dataType: string
		sourceColumn: discharge_disposition
	partition FactEncounter-partition = m
		mode: import
		source =
			let
			    Source = Table.FromRecords({
			        [encounter_key = 1, patient_key = 1, provider_key = 1, organization_key = 1, admission_date_key = 1, discharge_date_key = 1, encounter_class = "AMB", discharge_disposition = "Mock discharge_disposition 1"],
			        [encounter_key = 2, patient_key = 2, provider_key = 2, organization_key = 2, admission_date_key = 2, discharge_date_key = 2, encounter_class = "IMP", discharge_disposition = "Mock discharge_disposition 2"],
			        [encounter_key = 3, patient_key = 3, provider_key = 3, organization_key = 3, admission_date_key = 3, discharge_date_key = 3, encounter_class = "AMB", discharge_disposition = "Mock discharge_disposition 3"],
			        [encounter_key = 4, patient_key = 4, provider_key = 4, organization_key = 4, admission_date_key = 4, discharge_date_key = 4, encounter_class = "EMER", discharge_disposition = "Mock discharge_disposition 4"],
			        [encounter_key = 5, patient_key = 5, provider_key = 5, organization_key = 5, admission_date_key = 5, discharge_date_key = 5, encounter_class = "AMB", discharge_disposition = "Mock discharge_disposition 5"]
			    }),
			    #"Changed Type" = Table.TransformColumnTypes(Source, {
			        {"encounter_key", type text},
			        {"patient_key", type text},
			        {"provider_key", type text},
			        {"organization_key", type text},
			        {"admission_date_key", type text},
			        {"discharge_date_key", type text},
			        {"encounter_class", type text},
			        {"discharge_disposition", type text}
			    })
			in
			    #"Changed Type"

table FactProcedure
	// Description: Captures medical items, services, and supplemental benefits approved and furnished to enrollees.
	column procedure_key
		dataType: string
		sourceColumn: procedure_key
	column patient_key
		dataType: string
		sourceColumn: patient_key
	column provider_key
		dataType: string
		sourceColumn: provider_key
	column organization_key
		dataType: string
		sourceColumn: organization_key
	column date_key
		dataType: string
		sourceColumn: date_key
	column procedure_code
		dataType: string
		sourceColumn: procedure_code
	column procedure_description
		dataType: string
		sourceColumn: procedure_description
	partition FactProcedure-partition = m
		mode: import
		source =
			let
			    Source = Table.FromRecords({
			        [procedure_key = 1, patient_key = 1, provider_key = 1, organization_key = 1, date_key = 20260115, procedure_code = "99213", procedure_description = "Office Visit"],
			        [procedure_key = 2, patient_key = 2, provider_key = 2, organization_key = 2, date_key = 20260220, procedure_code = "85025", procedure_description = "CBC Test"],
			        [procedure_key = 3, patient_key = 3, provider_key = 3, organization_key = 3, date_key = 20260310, procedure_code = "CT001", procedure_description = "CT Scan"],
			        [procedure_key = 4, patient_key = 4, provider_key = 4, organization_key = 4, date_key = 20260425, procedure_code = "RX002", procedure_description = "Medication Request"],
			        [procedure_key = 5, patient_key = 5, provider_key = 5, organization_key = 5, date_key = 20260515, procedure_code = "99214", procedure_description = "Office Visit High"]
			    }),
			    #"Changed Type" = Table.TransformColumnTypes(Source, {
			        {"procedure_key", type text},
			        {"patient_key", type text},
			        {"provider_key", type text},
			        {"organization_key", type text},
			        {"date_key", type text},
			        {"procedure_code", type text},
			        {"procedure_description", type text}
			    })
			in
			    #"Changed Type"

table FactMedication
	// Description: Captures Part B drug requests and approvals.
	column medication_key
		dataType: string
		sourceColumn: medication_key
	column patient_key
		dataType: string
		sourceColumn: patient_key
	column provider_key
		dataType: string
		sourceColumn: provider_key
	column organization_key
		dataType: string
		sourceColumn: organization_key
	column date_key
		dataType: string
		sourceColumn: date_key
	column medication_code
		dataType: string
		sourceColumn: medication_code
	column medication_description
		dataType: string
		sourceColumn: medication_description
	partition FactMedication-partition = m
		mode: import
		source =
			let
			    Source = Table.FromRecords({
			        [medication_key = 1, patient_key = 1, provider_key = 1, organization_key = 1, date_key = 20260115, medication_code = "0001", medication_description = "Mock medication_description 1"],
			        [medication_key = 2, patient_key = 2, provider_key = 2, organization_key = 2, date_key = 20260220, medication_code = "0002", medication_description = "Mock medication_description 2"],
			        [medication_key = 3, patient_key = 3, provider_key = 3, organization_key = 3, date_key = 20260310, medication_code = "0003", medication_description = "Mock medication_description 3"],
			        [medication_key = 4, patient_key = 4, provider_key = 4, organization_key = 4, date_key = 20260425, medication_code = "0004", medication_description = "Mock medication_description 4"],
			        [medication_key = 5, patient_key = 5, provider_key = 5, organization_key = 5, date_key = 20260515, medication_code = "0005", medication_description = "Mock medication_description 5"]
			    }),
			    #"Changed Type" = Table.TransformColumnTypes(Source, {
			        {"medication_key", type text},
			        {"patient_key", type text},
			        {"provider_key", type text},
			        {"organization_key", type text},
			        {"date_key", type text},
			        {"medication_code", type text},
			        {"medication_description", type text}
			    })
			in
			    #"Changed Type"

table DimPatient
	// Description: Demographic and enrollment status details of the Medicare Advantage enrollees.
	column patient_key
		dataType: string
		sourceColumn: patient_key
	column mbi
		dataType: string
		sourceColumn: mbi
	column state
		dataType: string
		sourceColumn: state
	column is_active
		dataType: boolean
		sourceColumn: is_active
	column deceased_date
		dataType: dateTime
		sourceColumn: deceased_date
	partition DimPatient-partition = m
		mode: import
		source =
			let
			    Source = Table.FromRecords({
			        [patient_key = 1, mbi = "1EG4-TE5-MK2", state = "Mock state 1", is_active = true, deceased_date = #date(2026, 1, 15)],
			        [patient_key = 2, mbi = "2FH5-UG6-NL3", state = "Mock state 2", is_active = false, deceased_date = #date(2026, 2, 20)],
			        [patient_key = 3, mbi = "3GJ6-VH7-OM4", state = "Mock state 3", is_active = true, deceased_date = #date(2026, 3, 10)],
			        [patient_key = 4, mbi = "4HK7-WI8-PN5", state = "Mock state 4", is_active = false, deceased_date = #date(2026, 4, 25)],
			        [patient_key = 5, mbi = "5JL8-XJ9-QO6", state = "Mock state 5", is_active = true, deceased_date = #date(2026, 5, 15)]
			    }),
			    #"Changed Type" = Table.TransformColumnTypes(Source, {
			        {"patient_key", type text},
			        {"mbi", type text},
			        {"state", type text},
			        {"is_active", type logical},
			        {"deceased_date", type date}
			    })
			in
			    #"Changed Type"

table DimProvider
	// Description: Details of healthcare practitioners and providers.
	column provider_key
		dataType: string
		sourceColumn: provider_key
	column npi
		dataType: string
		sourceColumn: npi
	column qualification
		dataType: string
		sourceColumn: qualification
	partition DimProvider-partition = m
		mode: import
		source =
			let
			    Source = Table.FromRecords({
			        [provider_key = 1, npi = "NPI11111", qualification = "Physician"],
			        [provider_key = 2, npi = "NPI22222", qualification = "Specialist"],
			        [provider_key = 3, npi = "NPI33333", qualification = "Physician"],
			        [provider_key = 4, npi = "NPI44444", qualification = "Specialist"],
			        [provider_key = 5, npi = "NPI55555", qualification = "Physician"]
			    }),
			    #"Changed Type" = Table.TransformColumnTypes(Source, {
			        {"provider_key", type text},
			        {"npi", type text},
			        {"qualification", type text}
			    })
			in
			    #"Changed Type"

table DimOrganization
	// Description: Details of Medicare Advantage Organizations, Plan Sponsors, D-SNPs, and Employer Groups.
	column organization_key
		dataType: string
		sourceColumn: organization_key
	column contract_number
		dataType: string
		sourceColumn: contract_number
	column pbp_code
		dataType: string
		sourceColumn: pbp_code
	column organization_type
		dataType: string
		sourceColumn: organization_type
	column line_of_business
		dataType: string
		sourceColumn: line_of_business
	partition DimOrganization-partition = m
		mode: import
		source =
			let
			    Source = Table.FromRecords({
			        [organization_key = 1, contract_number = "H1001", pbp_code = "Mock pbp_code 1", organization_type = "MAO", line_of_business = "Mock line_of_business 1"],
			        [organization_key = 2, contract_number = "H2002", pbp_code = "Mock pbp_code 2", organization_type = "MAO", line_of_business = "Mock line_of_business 2"],
			        [organization_key = 3, contract_number = "H3003", pbp_code = "Mock pbp_code 3", organization_type = "1876 Cost Plan", line_of_business = "Mock line_of_business 3"],
			        [organization_key = 4, contract_number = "H4004", pbp_code = "Mock pbp_code 4", organization_type = "IRE", line_of_business = "Mock line_of_business 4"],
			        [organization_key = 5, contract_number = "H5005", pbp_code = "Mock pbp_code 5", organization_type = "Appeals Council", line_of_business = "Mock line_of_business 5"]
			    }),
			    #"Changed Type" = Table.TransformColumnTypes(Source, {
			        {"organization_key", type text},
			        {"contract_number", type text},
			        {"pbp_code", type text},
			        {"organization_type", type text},
			        {"line_of_business", type text}
			    })
			in
			    #"Changed Type"

table DimCondition
	// Description: Diagnosis codes associated with enrollees and determinations.
	column condition_key
		dataType: string
		sourceColumn: condition_key
	column diagnosis_code
		dataType: string
		sourceColumn: diagnosis_code
	partition DimCondition-partition = m
		mode: import
		source =
			let
			    Source = Table.FromRecords({
			        [condition_key = 1, diagnosis_code = "Mock diagnosis_code 1"],
			        [condition_key = 2, diagnosis_code = "Mock diagnosis_code 2"],
			        [condition_key = 3, diagnosis_code = "Mock diagnosis_code 3"],
			        [condition_key = 4, diagnosis_code = "Mock diagnosis_code 4"],
			        [condition_key = 5, diagnosis_code = "Mock diagnosis_code 5"]
			    }),
			    #"Changed Type" = Table.TransformColumnTypes(Source, {
			        {"condition_key", type text},
			        {"diagnosis_code", type text}
			    })
			in
			    #"Changed Type"

table DimDate
	// Description: Standard date dimension for time-based analysis and reporting periods.
	column date_key
		dataType: string
		sourceColumn: date_key
	column date
		dataType: dateTime
		sourceColumn: date
	column year
		dataType: int64
		sourceColumn: year
	column quarter
		dataType: string
		sourceColumn: quarter
	column month
		dataType: string
		sourceColumn: month
	column day
		dataType: int64
		sourceColumn: day
	partition DimDate-partition = m
		mode: import
		source =
			let
			    Source = Table.FromRecords({
			        [date_key = 20260115, date = #date(2026, 1, 15), year = 2026, quarter = 1, month = 1, day = 15],
			        [date_key = 20260220, date = #date(2026, 2, 20), year = 2026, quarter = 1, month = 2, day = 20],
			        [date_key = 20260310, date = #date(2026, 3, 10), year = 2026, quarter = 1, month = 3, day = 10],
			        [date_key = 20260425, date = #date(2026, 4, 25), year = 2026, quarter = 2, month = 4, day = 25],
			        [date_key = 20260515, date = #date(2026, 5, 15), year = 2026, quarter = 2, month = 5, day = 15]
			    }),
			    #"Changed Type" = Table.TransformColumnTypes(Source, {
			        {"date_key", type text},
			        {"date", type date},
			        {"year", Int64.Type},
			        {"quarter", type text},
			        {"month", type text},
			        {"day", Int64.Type}
			    })
			in
			    #"Changed Type"

relationship 'FactObservation_DimPatient_patient_key'
	fromTable: FactObservation
	fromColumn: patient_key
	toTable: DimPatient
	toColumn: patient_key
	cardinality: manyToOne

relationship 'FactObservation_DimProvider_provider_key'
	fromTable: FactObservation
	fromColumn: provider_key
	toTable: DimProvider
	toColumn: provider_key
	cardinality: manyToOne

relationship 'FactObservation_DimOrganization_organization_key'
	fromTable: FactObservation
	fromColumn: organization_key
	toTable: DimOrganization
	toColumn: organization_key
	cardinality: manyToOne

relationship 'FactObservation_DimDate_date_key'
	fromTable: FactObservation
	fromColumn: date_key
	toTable: DimDate
	toColumn: date_key
	cardinality: manyToOne

relationship 'FactEncounter_DimPatient_patient_key'
	fromTable: FactEncounter
	fromColumn: patient_key
	toTable: DimPatient
	toColumn: patient_key
	cardinality: manyToOne

relationship 'FactEncounter_DimProvider_provider_key'
	fromTable: FactEncounter
	fromColumn: provider_key
	toTable: DimProvider
	toColumn: provider_key
	cardinality: manyToOne

relationship 'FactEncounter_DimOrganization_organization_key'
	fromTable: FactEncounter
	fromColumn: organization_key
	toTable: DimOrganization
	toColumn: organization_key
	cardinality: manyToOne

relationship 'FactEncounter_DimDate_admission_date_key'
	fromTable: FactEncounter
	fromColumn: admission_date_key
	toTable: DimDate
	toColumn: date_key
	cardinality: manyToOne

relationship 'FactProcedure_DimPatient_patient_key'
	fromTable: FactProcedure
	fromColumn: patient_key
	toTable: DimPatient
	toColumn: patient_key
	cardinality: manyToOne

relationship 'FactProcedure_DimProvider_provider_key'
	fromTable: FactProcedure
	fromColumn: provider_key
	toTable: DimProvider
	toColumn: provider_key
	cardinality: manyToOne

relationship 'FactProcedure_DimOrganization_organization_key'
	fromTable: FactProcedure
	fromColumn: organization_key
	toTable: DimOrganization
	toColumn: organization_key
	cardinality: manyToOne

relationship 'FactProcedure_DimDate_date_key'
	fromTable: FactProcedure
	fromColumn: date_key
	toTable: DimDate
	toColumn: date_key
	cardinality: manyToOne

relationship 'FactMedication_DimPatient_patient_key'
	fromTable: FactMedication
	fromColumn: patient_key
	toTable: DimPatient
	toColumn: patient_key
	cardinality: manyToOne

relationship 'FactMedication_DimProvider_provider_key'
	fromTable: FactMedication
	fromColumn: provider_key
	toTable: DimProvider
	toColumn: provider_key
	cardinality: manyToOne

relationship 'FactMedication_DimOrganization_organization_key'
	fromTable: FactMedication
	fromColumn: organization_key
	toTable: DimOrganization
	toColumn: organization_key
	cardinality: manyToOne

relationship 'FactMedication_DimDate_date_key'
	fromTable: FactMedication
	fromColumn: date_key
	toTable: DimDate
	toColumn: date_key
	cardinality: manyToOne
